const mongoose = require("mongoose");

const mortalitySchema = new mongoose.Schema({
  location: String,
  date: String,
  p_scores_all_ages: Number,
  p_scores_15_64: Number,
  p_scores_65_74: Number,
  p_scores_75_84: Number,
  p_scores_85plus: Number,
  deaths_2020_all_ages: Number,
  average_deaths_2015_2019_all_ages: Number,
  deaths_2015_all_ages: Number,
  deaths_2016_all_ages: Number,
  deaths_2017_all_ages: Number,
  deaths_2018_all_ages: Number,
  deaths_2019_all_ages: Number,
  deaths_2010_all_ages: Number,
  deaths_2011_all_ages: Number,
  deaths_2012_all_ages: Number,
  deaths_2013_all_ages: Number,
  deaths_2014_all_ages: Number,
  deaths_2021_all_ages: Number,
  time: Number,
  time_unit: String,
  p_scores_0_14: Number,
  projected_deaths_since_2020_all_ages: Number,
  excess_proj_all_ages: Number,
  cum_excess_proj_all_ages: Number,
  cum_proj_deaths_all_ages: Number,
  cum_p_proj_all_ages: Number,
  p_proj_all_ages: Number,
  p_proj_0_14: Number,
  p_proj_15_64: Number,
  p_proj_65_74: Number,
  p_proj_75_84: Number,
  p_proj_85p: Number,
  cum_excess_per_million_proj_all_ages: Number,
  excess_per_million_proj_all_ages: Number,
  deaths_2022_all_ages: Number,
  deaths_2023_all_ages: Number,
  deaths_since_2020_all_ages: Number,
});

module.exports = mongoose.model(
  "MortalityData",
  mortalitySchema,
  "mortalityData"
);
